name: Build Check

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ENABLE_CUDA: [ON, OFF]
        ENABLE_OPENMP: [ON, OFF]
        ENABLE_ZSTD: [ON, OFF]
        BUILD_EXAMPLES: [ON, OFF]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Install CUDA Toolkit (if needed)
        if: matrix.ENABLE_CUDA == 'ON'
        run: |
          sudo apt install -y nvidia-cuda-toolkit
          echo "/usr/local/cuda/bin" >> $GITHUB_PATH
          nvcc --version  
      
      - name: Install zstd (if needed)
        if: matrix.ENABLE_ZSTD == 'ON'
        run: |
          sudo apt install -y build-essential zstd
      
      - name: Install OPENMP (if needed)
        if: matrix.ENABLE_OPENMP == 'ON'
        run: |
          sudo apt install -y build-essential libomp-dev

      - name: Set CUDA flag
        run: |
          if [[ "${{ matrix.ENABLE_CUDA }}" == "OFF" ]]; then
            echo "CUDA disabled by matrix"
            echo "ENABLE_CUDA=OFF" >> $GITHUB_ENV
          elif command -v nvcc >/dev/null 2>&1; then
            echo "CUDA detected"
            echo "ENABLE_CUDA=ON" >> $GITHUB_ENV
          else
            echo "CUDA requested but not found, disabling CUDA"
            echo "ENABLE_CUDA=OFF" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/my_project_install \
                   -DENABLE_CUDA=${{ env.ENABLE_CUDA }} \
                   -DENABLE_OPENMP=${{ matrix.ENABLE_OPENMP }} \
                   -DENABLE_ZSTD=${{ matrix.ENABLE_ZSTD }} \
                   -DBUILD_EXAMPLES=${{ matrix.BUILD_EXAMPLES }}
          make -j$(nproc)
          make install

      - name: Verify installation
        run: |
          echo "Installation directory: $HOME/my_project_install"
          ls -l $HOME/my_project_install/
          ls -l $HOME/my_project_install/bin/
