name: Build Check

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 在针对 main 的 PR 创建或更新时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出当前提交的代码

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libomp-dev

      - name: Detect CUDA and set options
        id: detect
        run: |
          if command -v nvcc >/dev/null 2>&1; then
            echo "CUDA detected"
            echo "ENABLE_CUDA=ON" >> $GITHUB_ENV
          else
            echo "CUDA not detected"
            echo "ENABLE_CUDA=OFF" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_CUDA=${{ env.ENABLE_CUDA }} -DENABLE_OPENMP=ON
          make -j$(nproc)
          make install
